fix: ci

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -16,6 +16,21 @@ jobs:
         with:
           ref: ${{ github.event.repository.default_branch }}
 
+      - name: Checkout to the branch of the tag
+        run: |
+          # check if git tag is the last commit of some branch
+          TAG=${{ github.ref_name }}
+          BRANCH=$(git branch --contains $TAG | grep -v HEAD | head -n 1 | sed 's/^* //' | sed 's/^  //')
+          LAST_COMMIT=$(git rev-parse $BRANCH)
+          TAG_COMMIT=$(git rev-list -n 1 $TAG)
+
+          if [[ "$LAST_COMMIT" != "$TAG_COMMIT" ]]; then
+            echo "ERROR: Tag $TAG is NOT the last commit of branch $BRANCH. Exiting.."
+            exit 1
+          fi
+
+          git checkout "$BRANCH"
+
       - name: Update CHANGELOG
         id: changelog
         uses: requarks/changelog-action@v1
@@ -29,8 +44,7 @@ jobs:
         run: |
           git config user.name github-actions
           git config user.email github-actions@github.com
-          # There is no local tag because we checked out the default branch
-          # git tag -d ${{ github.ref_name }}
+          git tag -d ${{ github.ref_name }}
           git push origin --delete ${{ github.ref_name }}
           git add CHANGELOG.md
           git commit -m "docs: update CHANGELOG.md for ${{ github.ref_name }} [skip ci]"
