ci: ruff better summary

diff --git a/.github/workflows/lint.yml b/.github/workflows/lint.yml
--- a/.github/workflows/lint.yml
+++ b/.github/workflows/lint.yml
@@ -7,9 +7,56 @@ jobs:
     name: ruff
     runs-on: ubuntu-latest
     steps:
-      - uses: actions/checkout@v3
-      - name: Lint with ruff 
-        uses: chartboost/ruff-action@v1
+      - uses: actions/checkout@v4
+      - name: Set up Python 3.11
+        uses: actions/setup-python@v4
         with:
-          src: "."
-          version: 0.1.0
+          python-version: 3.11
+      - name: Install ruff and requirements
+        run: |
+          pip3 install ruff==0.1.0
+      - name: Run ruff 
+        run: |
+          set +e  # Do not exit shell on ruff failure
+
+          echo "\`\`\`python" >> $GITHUB_STEP_SUMMARY
+          nonzero_exit=0
+          for file in ${{ steps.changed-python-files.outputs.all_changed_files }}; do
+            out=$(ruff check "$file" 2> ruff_stderr.txt)
+            exit_code=$?
+            err=$(<ruff_stderr.txt)
+
+            if [[ $exit_code -ne 0 ]]; then
+              nonzero_exit=$exit_code
+            fi
+
+            if [[ -n "$out" ]]; then
+              # Display the raw output in the step
+              echo "${out}"
+              # Display the Markdown output in the job summary
+              echo "${out}" >> $GITHUB_STEP_SUMMARY
+            fi
+            if [[ -n "$err" ]]; then
+              echo "${err}"
+              echo "${err}" >> $GITHUB_STEP_SUMMARY
+            fi
+
+            out=$(ruff check --diff "$file" 2> ruff_stderr.txt)
+            err=$(<ruff_stderr.txt)
+
+            if [[ -n "$out" ]]; then
+              # Display the raw output in the step
+              echo "${out}"
+              # Display the Markdown output in the job summary
+              echo "${out}" >> $GITHUB_STEP_SUMMARY
+            fi
+            if [[ -n "$err" ]]; then
+              echo "${err}"
+              echo "${err}" >> $GITHUB_STEP_SUMMARY
+            fi
+          done
+          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
+
+          # Exit with the first non-zero exit-code returned by ruff
+          # or just zero if all passed
+          exit ${nonzero_exit}
diff --git a/.github/workflows/styles-only-changed.yml b/.github/workflows/styles-only-changed.yml
--- a/.github/workflows/styles-only-changed.yml
+++ b/.github/workflows/styles-only-changed.yml
@@ -1,16 +1,14 @@
 name: Style check on changed files
 
 on:
-  pull_request:
-    branches:
-      - main
+  pull_request
 
 jobs:
   # ------------------------------------------------------------------------------------------------------------------------------------------------
   # Event `pull_request`: Compare the last commit of the main branch or last remote commit of the PR branch -> to the current commit of a PR branch.
   # ------------------------------------------------------------------------------------------------------------------------------------------------
   black-only-changed:
-    name: black-only-changed
+    name: Black
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v4
@@ -56,7 +54,7 @@ jobs:
           exit ${exit_code}
 
   isort-only-changed:
-    name: isort-only-changed
+    name: isort
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v4
@@ -103,7 +101,7 @@ jobs:
           exit ${exit_code}
 
   ruff-only-changed:
-    name: ruff-only-changed
+    name: ruff
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v4
@@ -131,20 +129,46 @@ jobs:
         if: steps.changed-python-files.outputs.any_changed == 'true'
         run: |
           set +e  # Do not exit shell on ruff failure
-          out=$(ruff check ${{ steps.changed-python-files.outputs.all_changed_files }} 2> ruff_stderr.txt)
-          exit_code=$?
-          err=$(<ruff_stderr.txt)
 
-          # Display the raw output in the step
-          echo "${out}"
-          echo "${err}"
-
-          # Display the Markdown output in the job summary
           echo "\`\`\`python" >> $GITHUB_STEP_SUMMARY
-          echo "${out}" >> $GITHUB_STEP_SUMMARY
-          echo "${err}" >> $GITHUB_STEP_SUMMARY
+          nonzero_exit=0
+          for file in ${{ steps.changed-python-files.outputs.all_changed_files }}; do
+            out=$(ruff check "$file" 2> ruff_stderr.txt)
+            exit_code=$?
+            err=$(<ruff_stderr.txt)
+
+            if [[ $exit_code -ne 0 ]]; then
+              nonzero_exit=$exit_code
+            fi
+
+            if [[ -n "$out" ]]; then
+              # Display the raw output in the step
+              echo "${out}"
+              # Display the Markdown output in the job summary
+              echo "${out}" >> $GITHUB_STEP_SUMMARY
+            fi
+            if [[ -n "$err" ]]; then
+              echo "${err}"
+              echo "${err}" >> $GITHUB_STEP_SUMMARY
+            fi
+
+            out=$(ruff check --diff "$file" 2> ruff_stderr.txt)
+            err=$(<ruff_stderr.txt)
+
+            if [[ -n "$out" ]]; then
+              # Display the raw output in the step
+              echo "${out}"
+              # Display the Markdown output in the job summary
+              echo "${out}" >> $GITHUB_STEP_SUMMARY
+            fi
+            if [[ -n "$err" ]]; then
+              echo "${err}"
+              echo "${err}" >> $GITHUB_STEP_SUMMARY
+            fi
+          done
           echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
 
-          # Exit with the exit-code returned by ruff
-          exit ${exit_code}
+          # Exit with the first non-zero exit-code returned by ruff
+          # or just zero if all passed
+          exit ${nonzero_exit}
 
