feat: remove tox dependency

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -10,7 +10,7 @@ jobs:
     strategy:
       matrix:
         os: [ubuntu-latest]
-        python-version: ['3.11']  # Can also use multiple versions
+        python-version: ['3.11']  # Can also test on multiple versions
 
     steps:
       - uses: actions/checkout@v3
@@ -21,6 +21,31 @@ jobs:
       - name: Install dependencies
         run: |
           python -m pip install --upgrade pip
-          pip install tox tox-gh-actions
-      - name: Test with tox
-        run: tox
+          pip3 install -r requirements.txt -r requirements_dev.txt
+          pip3 install -e .
+      - name: Run pytest
+        run: |
+          set +e  # Do not exit shell on pytest failure
+          out=$(pytest 2> stderr.txt)
+          exit_code=$?
+          err=$(<stderr.txt)
+
+          # Display the raw output in the step
+          echo "${out}"
+          echo "${err}"
+
+          # Display the Markdown output in the job summary
+          echo "\`\`\`python" >> $GITHUB_STEP_SUMMARY
+          echo "${out}" >> $GITHUB_STEP_SUMMARY
+          echo "${err}" >> $GITHUB_STEP_SUMMARY
+          if [[ $exit_code -eq 5 ]]
+          then
+            echo
+            echo 'WARNING: No tests were run and it is considered as success' >> $GITHUB_STEP_SUMMARY
+            echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
+            exit 0
+          else
+            echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
+            # Exit with the exit-code returned by pytest
+            exit ${exit_code}
+          fi
